### ISSUE TITLE
Ошибка в методе линейного поиска с барьером 

### ISSUE THREAD

**Issue by ZetoOfficial** [DSW-DWA/Algoritms#1]
**Ожидаемый результат:**
Время работы линейного поиска **с** бар**ье**ром

**Фактический результат:**
Время работы линейного поиска **c** бар**еь**ром

https://github.com/DSW-DWA/Algorithms/blob/main/Lab_5/Lab_5/Search.cs#L40

**Comment by DSW-DWA** [comment]
Спасибо, коллега
